hDP/urls.py
from django.conf.urls.defaults import *
from hDP import views

urlpatterns = patterns('hDP.views',
        (r'^test/', "test"),
        (r'^test2/', "test2"),
        (r'^$', "index"),
)

labme/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^weblab/', include('weblab.urls')),
    (r'^hDP/', include('hDP.urls')),
    (r'^genome/', include('genome.urls')),
    (r'^accounts/', include('registration.backends.default.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^login/', include(admin.site.urls)),
    (r'^shoebox/', include('shoebox.urls')),
    (r'^eQTL/', include('eQTL.urls')),
    (r'^hNP/', include('saresity.urls')),
    (r'^search/', include('haystack.urls')),
    (r'^$', include('shoebox.urls')),
)

urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^weblab/', include('weblab.urls')),
    (r'^hDP/', include('hDP.urls')),
    (r'^genome/', include('genome.urls')),
    (r'^accounts/', include('registration.backends.default.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^login/', include(admin.site.urls)),
    (r'^shoebox/', include('shoebox.urls')),
    (r'^eQTL/', include('eQTL.urls')),
    (r'^hNP/', include('saresity.urls')),
    (r'^search/', include('haystack.urls')),
    (r'^$', include('weblab.urls')),
)

hDP/models.py
from django.db import models

# Create your models here

class Population(models.Model):
    """
    Table containing information about the various HGDP populations
    """
    population_name = models.CharField(max_length=250)
    nickname = models.CharField(max_length=3)
    latitude = models.SmallIntegerField()
    longitude = models.SmallIntegerField()
    comment = models.CharField(max_length=250)

    def __unicode__(self):
        return(self.population_name)

class Individual(models.Model):
    """
    Table maping HGDP IDS to population as well as gender
    Ignore origin because except for a few cases all come from origin
    """
    GENDER = (
            (0, 'Male'),
            (1, 'Female')
            )
    hgdp_id = models.CharField(max_length=10, primary_key = True)
    gender = models.SmallIntegerField(choices=GENDER)
    population_name = models.ForeignKey(Population)

    def __unicode__(self):
        return(self.hgdp_id)

class Genotypes(models.Model):
    """
    Oh god so much data.  See if you can use pyTables for this
    """
    pass

class Phenotypes(models.Model):
    pass

hDP/forms.py
from django import forms

class SNPForm(forms.Form):
    rsID = forms.CharField(max_length=50)

hDP/views.py
"""
Views for the webGl globe and the Human Geneome Diversity Panel
"""
import json, random
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from hDP.models import Population, Individual
from forms import SNPForm

def index(request):
    populations = Population.objects.all()
    if request.method == 'POST':
        rs_query = request.POST['rsID']
        response = [[random.random(), pop.latitude, 
            pop.longitude]for pop in populations]
        print(len(response))
        response = json.dumps(response)
        return(HttpResponse(response, mimetype="application/json"))
    else:
        response = [[random.random(), pop.latitude, pop.longitude]for pop in populations]
        response = json.dumps(response)
        form = SNPForm()
        return render_to_response('webgl.html',{'data':response, 'form':form,},
                context_instance=RequestContext(request))


def test(request):
    return(render_to_response('test.html',
        context_instance=RequestContext(request)))

def test2(request):
    return(render_to_response('test2.html',
        context_instance=RequestContext(request)))

hDP/templates/badtest.html
{% extends "base.html" %}
{% block header %}
<script type="text/javascript"
    src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/csrf.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/Three.js"></script>
{% endblock %}

{% block content %}
<div id="test"></div>
<div id="container"></div>
<script type="text/javascript">
    // set scene size
    var WIDTH = 400,
        HEIGHT = 300;
    // set some camera attirbutes
    var VIEW_ANGLE = 45, 
        ASPECT = WIDTH/HEIGHT, 
        NEAR = 0.1,
        FAR = 10000;

    var $container = $('#container');
    var renderer = new THREE.WebGLRenderer();
    var camera = new THREE.Camera(VIEW_ANGLE,
            ASPECT,
            NEAR,
            FAR);
    var scene = new THREE.Scene();
    camera.position.z = 300;
    // start the renderer
    renderer.setSize(WIDTH, HEIGHT);
    $container.append(renderer.domElement);

    var radius = 50, segments = 16, rings = 16;
    var sphere = new THREE.Mesh(
            new THREE.Sphere(radius, segments, rings), 
            SphereMaterial);
    var SphereMaterial = new THREE.MeshLambertMaterial({
        color: 0xCC0000
        });
    console.log(SphereMaterial);
    // create a point light
    var pointLight = new THREE.PointLight( 0xFFFFFF );
    // set its position
    pointLight.position.x = 10;
    pointLight.position.y = 50;
    pointLight.position.z = 130;
    scene.addChild(sphere);
    // add to the scene
    scene.addLight(pointLight);
    console.log(scene);
    renderer.render(scene, camera);


</script>
{% endblock %}

hDP/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %} weblab {% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}styles/base.css" media="screen" />
        {% block header %} {% endblock %}
    </head>

<body>
    <div id="navigation">
        <ul id = "nav">
            <li><a href="/">Home </a> </li>
            <li><a href="/hDP/">Test</a></li>
            <li><a href="https://github.com/jeffhsu3">Github</a></li>
            <li><a href="/weblab/">Weblab </a>
        {% if user.is_authenticated %}
            <li><a href="/signout/">Signout </a></li> 
        {% else %}
            <li><a href="/login/">Login</a></li> 
        {% endif %}
    </div>


    <div id="content">
        {% block content %}{% endblock %}
    </div>


    <div id="footer">
    </div>
</body>
</html>

hDP/templates/test.html
{% extends "base.html" %}
{% block header %}
<script type="text/javascript"
    src="{{ STATIC_URL }}js/jquery.min.js"></script>
<script src="{{ STATIC_URL}}js/jquery-ui.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/csrf.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/Three.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/RequestAnimationFrame.js"></script>
<script>
    jQuery(document).ready(function() {
        jQuery("button").button();
        jQuery('#pause').click(function() {
            event.preventDefault();
            document.removeEventListener( 'mousedown', onDocumentMouseDown, false );
            });
        jQuery('#rotate-right').click(function() {
            event.preventDefault();
            theta += 90;
        });
        jQuery('#rotate-left').click(function(){
            event.preventDefault();
            theta -= 90;
        });

        jQuery('#rotate-up').click(function(){
            event.preventDefault();
            phi += 90;
        });
    });
</script>
{% endblock %}

{% block content %}
<div id="container">
    <div id="controls">
        <button id="pause">Pause</button>
        <button id="rotate-right">Rotate Right</button> 
        <button id="rotate-left">Rotate Left</button>
        <button id="rotate-up"> Rotate Up </button>
        <button id="rotate-down"> Rotate Up </button>
        <button id="save"> Save </button>
    </div>
</div>
<script type="text/javascript">
    var camera, scene, renderer;
    var projector, plane, cube;
    var mouse2D, mouse3d, ray, rollOveredFace, isShiftDown = false,
    theta = 45,phi=60,radious=1600,onMouseDownTheta = 45, onMouseDownPhi=60, isCtrlDown = false, isMouseDown = false;
    var rollOverMesh, rollOverMaterial, voxelPosition = new THREE.Vector3(), tmpVec = new THREE.Vector3();
    var cubeGeo, cubeMaterial;
    var i, intersector;

    init();
    animate();

function init(){
    container = document.getElementById( 'container' );
    camera = new THREE.Camera(40, window.innderWidth/window.innerHeight,1,100000);
    // Camera
    camera.position.x = radious * Math.sin(theta * Math.PI/360)
        Math.cos(phi*Math.PI/360);
	camera.position.y = radious * Math.sin( phi * Math.PI / 360 );
	camera.position.z = radious * Math.cos( theta * Math.PI / 360 ) * Math.cos( phi * Math.PI / 360 );
    camera.target.position.y = 200;

    scene = new THREE.Scene();
    // roll-over transparent helpers
    rollOverCube = new THREE.Cube( 50, 50, 50 );
    rollOverMaterial = new THREE.MeshBasicMaterial( { color: 0xff0000,
            opacity: 0.5, transparent: true });
    rollOverMesh = new THREE.Mesh( rollOverCube, rollOverMaterial);
    scene.addObject(rollOverMesh);

    // cubes
    cubeGeo = new THREE.Cube( 50, 50, 50);
    cubeMaterial = new THREE.MeshBasicMaterial( { color: 0x880000,
            shading:THREE.FlatShading})
    // picking
    projector = new THREE.Projector();

    // Grid
    plane = new THREE.Mesh( new THREE.Plane(1000, 1000, 20, 20), new
            THREE.MeshBasicMaterial( { color: 0x555555, wireframe: true } ));
    plane.rotation.x = - 90 * Math.PI /180;
    scene.addObject(plane);
    mouse2D = new THREE.Vector3(0,1000, 0.5);
    ray = new THREE.Ray( camera.position, null);

    // Lights

    var ambientLight = new THREE.AmbientLight(0x606060);
    scene.addLight(ambientLight);
    var directionalLight = new THREE.DirectionalLight(0xffffff);
    directionalLight.position.x = Math.random() - 0.5;
    directionalLight.position.y = Math.random() - 0.5;
    directionalLight.position.z = Math.random() - 0.5;
    directionalLight.position.normalize();
    scene.addLight( directionalLight );
    // Why 2?

    var directionalLight = new THREE.DirectionalLight( 0x808080 );
    directionalLight.position.x = Math.random() - 0.5;
    directionalLight.position.y = Math.random() - 0.5;
    directionalLight.position.z = Math.random() - 0.5;
    directionalLight.position.normalize();
    scene.addLight( directionalLight );

    renderer = new THREE.WebGLRenderer( { antialias: true } );
    renderer.setSize( window.innerWidth, window.innerHeight );

    container.appendChild( renderer.domElement );
    document.addEventListener( 'mousemove', onDocumentMouseMove, false );
    document.addEventListener( 'mousedown', onDocumentMouseDown, false );
    document.addEventListener( 'keydown', onDocumentKeyDown, false );
    document.addEventListener( 'keyup', onDocumentKeyUp, false );
    document.addEventListener( 'mousewheel', onDocumentMouseWheel, false);
}

function getRealIntersector( intersects ){
    for( i = 0; i < intersects.length; i++ ) {
        intersector = intersects[ i ];
        if ( intersector.object != rollOverMesh ) {
            return intersector;
        }
    }

    return null;
}

function setVoxelPosition( intersector ) {
    tmpVec.copy( intersector.face.normal );
    voxelPosition.add( intersector.point, intersector.object.matrixRotationWorld.multiplyVector3( tmpVec ) );
    voxelPosition.x = Math.floor( voxelPosition.x / 50 ) * 50 + 25;
    voxelPosition.y = Math.floor( voxelPosition.y / 50 ) * 50 + 25;
    voxelPosition.z = Math.floor( voxelPosition.z / 50 ) * 50 + 25;

}


function onDocumentMouseMove( event ) {
    event.preventDefault();
    // Need to update when the radious changes
    /*
    if ( isMouseDown ){
        theta = - (( event.clientX - onMouseDownPosition.x) * 0.5) +
            onMouseDownTheta
    }
    */
    mouse2D.x = ( event.clientX / window.innerWidth ) * 2 - 1;
    mouse2D.y = - ( event.clientY / window.innerHeight ) * 2 + 1;
}

function onDocumentMouseDown( event ) {
    event.preventDefault();
    var intersects = ray.intersectScene( scene );
    if ( intersects.length > 0 ) {
        intersector = getRealIntersector( intersects );
        // delete cube
        if ( isCtrlDown ) {
            if ( intersector.object != plane ) {
                scene.removeObject( intersector.object );
            }
        // create cube
        } else {
            intersector = getRealIntersector( intersects );
            setVoxelPosition( intersector );
            var voxel = new THREE.Mesh( cubeGeo, cubeMaterial );
            voxel.position.copy( voxelPosition );
            voxel.matrixAutoUpdate = false;
            voxel.updateMatrix();
            scene.addObject( voxel );
        }

    }
}

function onDocumentMouseUp( event ) {
    event.preventDefault();
    isMouseDown = false;

    

}



function onDocumentKeyDown( event ) {
    switch( event.keyCode ) {
        case 16: isShiftDown = true; break;
        case 17: isCtrlDown = true; break;
    }
}

function onDocumentKeyUp( event ) {
    switch( event.keyCode ) {
        case 16: isShiftDown = false; break;
        case 17: isCtrlDown = false; break;
    }
}

function onDocumentMouseWheel( event ) {
    radious -= event.wheelDeltaY;
    camera.position.x = radious * Math.sin( theta * Math.PI / 360 ) * Math.cos( phi * Math.PI / 360 );
    camera.position.y = radious * Math.sin( phi * Math.PI / 360 );
    camera.position.z = radious * Math.cos( theta * Math.PI / 360 ) * Math.cos( phi * Math.PI / 360 );
    camera.updateMatrix();
    render();
}

function interact() {
}

function animate() {
    requestAnimationFrame( animate );
    render();
}

function render() {
    if ( isShiftDown ) {
        theta += mouse2D.x * 3;
    }
    mouse3D = projector.unprojectVector( mouse2D.clone(), camera );
    ray.direction = mouse3D.subSelf( camera.position ).normalize();
    var intersects = ray.intersectScene( scene );
    if ( intersects.length > 0 ) {
        intersector = getRealIntersector( intersects );
        if ( intersector ) {
            setVoxelPosition( intersector );
            rollOverMesh.position = voxelPosition;
        }
    }
    camera.position.x = radious * Math.sin(theta * Math.PI/360)
        Math.cos(phi*Math.PI/360);
	camera.position.y = radious * Math.sin( phi * Math.PI / 360 );
	camera.position.z = radious * Math.cos( theta * Math.PI / 360 ) * Math.cos( phi * Math.PI / 360 );
    renderer.render( scene, camera );

}
</script>
{% endblock %}

hDP/templates/test2.html
{% extends "base.html" %}
{% block header %}
<script type="text/javascript"
    src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/csrf.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/Three.js"></script>
{% endblock %}

{% block content %}
<div id="test"></div>
<div id="container"></div>
<script type="text/javascript">
// 3d vars.
var camera;
var scene;
var renderer;
 
// size
var WIDTH 				= 800;
var HEIGHT 				= 600;
 
var circleColours 		= [0x0099CC, 0xCCCCCC, 0x9900CC];
var colourIndexToUse 	= 0;
var fadeAmount 			= 0.0000000005;
 
// used to tell when to draw.
var shouldDraw 			= false;
 
// mouse coordinates.
var mouseX;
var mouseY;
 
setInterval( invalidate, 10 );
 
function init() {
	camera= new THREE.Camera( 75, WIDTH / HEIGHT, 1, 10000 );
	scene= new THREE.Scene();
	renderer= new THREE.CanvasRenderer();
	renderer.setSize( WIDTH, HEIGHT );
 
	camera.position.z= 700;
	document.body.appendChild( renderer.domElement );
}
 
function invalidate()
{
	if(shouldDraw) draw();
	// fade all the current circles.
	fade();
	// render it all.
	renderer.render( scene, camera );
}
 
function draw() {
	 for(var i = 0; i &lt; 5; ++i)
	 {
		 var particle 			= new THREE.Particle( new THREE.ParticleCircleMaterial( circleColours[colourIndexToUse], Math.random() ) );
		 particle.position.x 	= i == 0 ? mouseX - 500 : mouseX - 500 * (Math.random() * 1.5);
		 particle.position.y 	= i == 0 ? mouseY - 500 : mouseY - 500 * (Math.random() * 1.5);
		 particle.position.z 	= mouseX * Math.random();
		 particle.scale.x 		= i == 0 ? particle.scale.y = Math.random() * 50 : particle.scale.y = Math.random() * 5;
	     scene.addObject( particle );
	 }
}
 
/*
 * This fades all the existing objects in the scene.
 */
function fade() {
	for(var i = 0; i &lt; scene.objects.length; ++i)
	{
		var prevAlpha = scene.objects[i].material[0].color.a;
		if(prevAlpha != 0)
		{
			var newMat= new THREE.ParticleCircleMaterial( circleColours[colourIndexToUse], prevAlpha - fadeAmount );
			scene.objects[i].material[0] 	= newMat;
		}
		else scene.removeObject(scene.objects[i]);
	}
}
 
function setMousePosition(x, y)
{
	mouseX 				= x;
	mouseY 				= y;
 
	camera.position.x 	+= (mouseX - camera.position.x) * .045;
	camera.position.y 	+= (-mouseY - camera.position.y) * .045;
}
 
jQuery(document).ready(function() {
	$('canvas').mousemove(function(e) { setMousePosition(e.pageX, e.pageY); } );
	$('canvas').mousedown(function(e) { shouldDraw = true;  } );
	$('canvas').mouseup(function(e)   { shouldDraw = false; } );
});
 
init();
</script>
{% endblock %}

hDP/templates/webgl.html
{% extends "base.html" %}
{% load compress %}
{% block header %}
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}styles/globe.css" />
    <script type="text/javascript"
        src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
    <script type="text/javascript" src="{{STATIC_URL}}js/csrf.js"></script>
    <script type="text/javascript">
    var getrsID = function() {
        event.preventDefault();
        var rsID = jQuery("#id_rsID").val();
        if (rsID != ""){
            var message = {rsID:rsID};
            var args = {type:"POST", url:"/hDP/", data:message,dataType:"json", success:done};
            jQuery.ajax(args);
        }
        else {
            alert("Need to input a SNP");
        }
    };
    $(document).ready(function() {
            $('#snpform').hide();
            $('#rsID-show').click(function() {
                event.preventDefault();
                $('#snpform').show('fast');
	            document.removeEventListener( 'mousedown', onDocumentMouseDown, false );
                });
            });
    </script>
{% endblock %}


{% block content %}
<div id="container"></div>
<div id="info">
    <strong>WebGL Globe</strong><br />
    Created by the <em>Google Data Arts Team</em><br />
    Released under the <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License</a>
</div>
<div id="rsID">
    <p><a href="#" id="rsID-show">Change SNP</a></p>
<form action="/hDP/", method="post", id="snpform">
        {% csrf_token %}
        {{form}}
        <p id="sendwrapper"><input type="submit" value="Send"
        id="sendbutton"/></p>
</form>
<script type="text/javascript">
    $('#snpform').submit(getrsID);
</script>
</div>
<div id="more">
    Minor Allele Frequencies from the Human Diversity Genetics Panel.
</div>
{% compress js %}
<script type="text/javascript">
    var data = {{ data }};
    var texture = "{{STATIC_URL}}textures/world.jpg";

    var done = function(res, status) {
        if (status=="success"){
            var data = res;
            geometry = new Cube( 0.75, 0.75, 1 );
            for ( var i = 0; i < geometry.vertices.length; i ++ ) {
                var vertex = geometry.vertices[ i ];
                vertex.position.z += 0.5;
            }
            point = new THREE.Mesh( geometry ); 
            point.geometry.__dirtyVerticies=true;
            point.geometry.__dirtyNormals=true;
            pointsGeometry = new THREE.Geometry();
            scene.removeObject(points);
            plotData(data);
	        document.addEventListener( 'mousedown', onDocumentMouseDown, false );
            $('#snpform').hide('fast');
            renderer.render();
        }
        else {
            alert("Cookies are required for proper viewing");
        }
    };
</script>
<script type="text/javascript" src="{{STATIC_URL}}js/RequestAnimationFrame.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/ThreeWebGL.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/ThreeExtras.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}globe.js"></script>
{% endcompress %}

{% endblock %}