labme/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^weblab/', include('weblab.urls')),
    (r'^hDP/', include('hDP.urls')),
    (r'^genome/', include('genome.urls')),
    (r'^accounts/', include('registration.backends.default.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^login/', include(admin.site.urls)),
    (r'^shoebox/', include('shoebox.urls')),
    (r'^eQTL/', include('eQTL.urls')),
    (r'^hNP/', include('saresity.urls')),
    (r'^search/', include('haystack.urls')),
    (r'^$', include('shoebox.urls')),
)

urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^weblab/', include('weblab.urls')),
    (r'^hDP/', include('hDP.urls')),
    (r'^genome/', include('genome.urls')),
    (r'^accounts/', include('registration.backends.default.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^login/', include(admin.site.urls)),
    (r'^shoebox/', include('shoebox.urls')),
    (r'^eQTL/', include('eQTL.urls')),
    (r'^hNP/', include('saresity.urls')),
    (r'^search/', include('haystack.urls')),
    (r'^$', include('weblab.urls')),
)

weblab/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from tastypie.api import Api
from weblab.api import (SampleResource, UserResource, LabResource,
                        SequenceResource, SequenceFolderResource,
                        FeatureLocationResource, SeqFeatureResource)


v1_api = Api(api_name = 'v1')
v1_api.register(SampleResource())
v1_api.register(UserResource())
v1_api.register(LabResource())
v1_api.register(SequenceResource())
v1_api.register(SequenceFolderResource())
v1_api.register(FeatureLocationResource())
v1_api.register(SeqFeatureResource())


urlpatterns = patterns(
        '',
        (r'^locations', "weblab.views.locations"),
        (r'^reagents', "weblab.views.reagents"),
        (r'^samples', "weblab.views.samples"),
        (r'^animals', "weblab.views.animals"),
        (r'^signout/', "weblab.views.signout"), 
        (r'^developers/', 'django.views.generic.simple.direct_to_template',
         {'template':'developers.html'}),
        (r'^about', "weblab.views.about"),
        (r'^api/', include(v1_api.urls)),
        (r'^sample_request', "weblab.views.sample_request"),
        (r'^search/', include('haystack.urls')),
        (r'^accounts/', include('registration.backends.default.urls')),
        (r'^experiment/', "weblab.views.experiment"),
        (r'^sequence/', "weblab.views.sequences"),
        (r'^$', "weblab.views.index"),
        )

weblab/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxLengthValidator

# Accelrating Science, Medicine and Industrial Chemical Managment 

# :TODO add default none storage


class Location(models.Model):
    """
    Location is room/building/lab/university etc.
    In addition contains a JSON field that has the layout of the location,
    including objects such as storage and machines.  
    """
    name = models.CharField(max_length=250)
    description = models.TextField('additional details')

    def __unicode__(self):
        return(self.name)


class Storage(models.Model):
    """
    Storage is an identifier for anything that contain multiple samples or
    reagents. 
    """
    name = models.CharField(max_length=250)
    location = models.ForeignKey(Location, default=None, null=True, blank=True,
            on_delete=models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now_add=True)
    parent_storage = models.ForeignKey('self', default=None, null=True,
                                       blank=True, on_delete=models.SET_NULL)

    def __unicode__(self):
        return(self.name[:30])

class Sample(models.Model):
    """ Samples are unique
    Should sample names be unique?
    """
    sub_date = models.DateTimeField('submission date')
    storage = models.ForeignKey(Storage,default=None, null=True, blank=True,
            on_delete=models.SET_NULL)
    name = models.CharField(max_length=250)
    owner = models.ForeignKey(User, related_name='sample_owner', default=None,
            null=True)
    viewable = models.ManyToManyField(User, default=None,blank=True, 
            related_name='sample_viewable', db_column='viewable_id')
    description = models.TextField('additional details')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return(self.name)


class Animal(models.Model):
    """ Subclass of samples
    """
    name = models.CharField(max_length=250)
    date_of_birth = models.DateTimeField('date of animal')
    strain = models.CharField(max_length=250)
    sac_date = models.DateTimeField('Sacrifice date of animal')

    def __unicode__(self):
        return(self.name)


class Strain(models.Model):
    """ Strain of a biological sample
    """
    pass

class Vendor(models.Model):
    """ Vendor API
    """
    vendor_name = models.CharField(max_length = 250)

    def __unicode__(self):
        return(self.name)

class Reagent(models.Model):
    """Chemicals or materials used for analysis.
    """
    name = models.CharField(max_length = 250)
    # :TODO have a pre-generate list ov vendors
    vendor = models.ForeignKey(Vendor)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

class Assay(models.Model):
    """A biological assay
    """
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


class Experiment(models.Model):
    """A class defining an experiment and associated samples
    """
    name = models.CharField(max_length = 250)
    description = models.TextField('additional details') 
    samples = models.ManyToManyField(Sample)
    created = models.DateTimeField(auto_now_add=True)


    def __unicode__(self):
        return(self.name)


class Lab(models.Model):
    """
    Model for individual laboratories, helps for setting permissions.
    """
    labname = models.CharField(max_length=200)
    members = models.ManyToManyField(User, related_name='lab_member')
    managers = models.ManyToManyField(User, related_name='lab_manager')

    def __unicode__(self):
        return(self.labname)

class Protocol(models.Model):
    """ Established protocols
    """
    pass


class SeqFeature(models.Model):
    """ A sequence feature such as a restriction site, gene, promoter,
    enhancer etc.
    """
    name = models.CharField(max_length=250
)
    seq = models.CharField(max_length=10000, null=True, blank=True)
    description = models.TextField()
    owner = models.ForeignKey(User, related_name='feat_owner',
                              default=None, blank=True, null=True)

    def __unicode__(self):
        return(self.name)


class Sequence(models.Model):
    """
    Generic sequences
    :TODO need to set a max sequence
    """
    KNOWN_ALPHABET = ((u'D', 'DNA'), (u'P','Protein'), (u'R', 'RNA'))
    seq = models.TextField('GenericSequence',
                           validators=[MaxLengthValidator(40000)])
    name = models.CharField(max_length=250)
    keyword = models.CharField(max_length=400, blank=True)
    description = models.TextField(max_length=20000, blank=True)
    owner = models.ForeignKey(User, related_name='seq_owner', default=None)
    alphabet = models.CharField(max_length=1, choices=KNOWN_ALPHABET)
    features = models.ManyToManyField(SeqFeature, through="FeatureLocation",
                                     null = True, blank = True)
    # Need to validate that feature_s and feature_e are the same length


    def __unicode__(self):
        return(self.name)

    def isValid(self):
        """ Server-side check on sequence similarity
        """
        self.seq = self.seq.strip()
        if self.alphabet == u'P':
            pass
        elif self.alphabet == u'D':
            d = ('A','G','C','T','a','g','c','t', 'N', 'n')
            for x in self.seq:
                if x not in d:
                   return(False)
            return(True)



class FeatureLocation(models.Model):
    """ Through table for feature sequence location. This should still have a
    name.
    """
    name = models.CharField(max_length=250)
    seq = models.ForeignKey(Sequence, related_name='featurelocations')
    feature = models.ForeignKey(SeqFeature, blank=True, null=True)
    # 0 for + strand 1 for - strand
    orientation = models.IntegerField(max_length = 1, blank=True, null=True)
    start = models.IntegerField()
    end = models.IntegerField()

    def __unicode__(self):
        #return('what')
        return(self.seq.name + "-" + self.feature.name)


class SequenceFolder(models.Model):
    """ User-organized sequences and samples
    """
    name = models.CharField(max_length=250)
    owner = models.ForeignKey(User, related_name='sequence_owner', default=None)
    # :FIX Change this to One to One?
    sequences = models.ManyToManyField(Sequence, related_name='folder_seq',
                                       default=None, blank=True)

    def __unicode__(self):
        return(self.name)

    def save(self, *args, **kwargs): 
        super(SequenceFolder, self).save(*args, **kwargs) 

weblab/forms.py
from django import forms
from haystack.forms import SearchForm
from weblab.models import Sample, Sequence, SequenceFolder


class SequenceField(forms.Field):
    def to_python(self, value):
        # Do this here or elsewhere?
        value = str(value)
        value = value.replace(" ", "").replace("\n", "")
        return(value)

    def validate(self, value):
        """Check if value consists of only valid sequences"""
        super(SequenceField, self).validate(value)


class TastypieM2MField(forms.Field):
    """ Custome validation for tastypie many to many uri relationships
    """
    def to_python(self, value):
        if value:
            value = list(value)
            return(value)
        else:
            return(u'')


class ExperimentSubmissionForm(forms.Form):
    name = forms.CharField(max_length = 255, initial="" )
    samples = forms.CharField(label='samples',
            widget=forms.TextInput(attrs={'placeholder':'Sample Name'}))
    sample_pk = forms.IntegerField(widget=forms.MultipleHiddenInput())


class BasicSearchBar(SearchForm):
    def search(self):
        sqs = super(BasicSearchBar, self).search()
        return sqs

class SampleForm(forms.Form):
    name = forms.CharField(max_length = 255, initial="")
    folder = forms.CharField(max_length = 255, initial="")


class SequenceForm(forms.Form):
    name = forms.CharField(max_length=250)
    seq = SequenceField()
    alphabet = forms.CharField(max_length=1)
    keyword = forms.CharField(max_length=400, required=False)
    description = forms.CharField(max_length=20000, required=False)
    folderSeq = TastypieM2MField()
    featurelocations = TastypieM2MField(required=False)

    def clean(self):
        cleaned_data = self.cleaned_data
        print(cleaned_data)
        seq = cleaned_data.get("seq")
        alphabet = cleaned_data.get("alphabet")

        if alphabet == u'P':
            pass
        elif alphabet == u'D':
            d = ('A','G','C','T','N')
            if seq:
                for letter in seq:
                    if letter.upper() not in d:
                        msg = u"Invalid letter in DNA sequnce"
                        self._errors["seq"] = self.error_class([msg])
                        self._errors["alphabet"] = self.error_class([msg])
                        del cleaned_data["seq"]
                        del cleaned_data["alphabet"]
                        break
                    else: pass
            else:
                msg = u"Must have sequence"
                self._errors["seq"] = self.error_class([msg])

        return cleaned_data

class FeatureLocationForm(forms.Form):
    start = forms.IntegerField()
    end = forms.IntegerField()

    def clean(self):
        # Checks to make sure start and end lie within the sequence
        pass

weblab/views.py
import json

from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import logout

from weblab.models import Sample, Location, Storage, Experiment
from weblab.models import SequenceFolder
from weblab.forms import ExperimentSubmissionForm
from weblab.encoders import folders_to_json

def index(request):
    return render_to_response('weblab.html',
            context_instance=RequestContext(request))

@login_required(login_url='/weblab/login/')
def locations(request):
    return render_to_response('locations.html',
            context_instance=RequestContext(request))

@login_required(login_url='/weblab/accounts/login/')
def reagents(request):
    return render_to_response('reagents.html',
                              context_instance=RequestContext(request))

def about(request):
    return render_to_response('about.html', 
                              context_instance=RequestContext(request))

def developers(request):
    return render_to_response('developers.html',
                              context_instance=RequestContext(request))

def clients(request):
    return render_to_response('clients.html',
                              context_instance=RequestContext(request))

def animals(request):
    pass

@login_required(login_url='/weblab/accounts/login/')
def samples(request):
    """ Contains a view for both animal and other samples
    :TODO have function to return next set of samples
    """
    if request.user.is_authenticated():
        samples = Sample.objects.filter(viewable=request.user) 
    else:
        # Should I display public samples
        samples = Sample.objects.order_by("-created")[0:10]
    return render_to_response('samples.html', {'samples': samples,},
            context_instance=RequestContext(request))

def sample_detail(request, sample_id):
    sample = get_object_or_404(Sample, pk=sample_id)
    return render_to_response('sample_detail.html', {'sample': sample},
            context_instance=RequestContext(request))


def signout(request):
    logout(request)
    return HttpResponseRedirect('/weblab/')


def experiment(request):
    """ Contains view to add samples to experiments
    """
    if request.POST:
        print(request.POST)
        form = ExperimentSubmissionForm(request.POST)
        print(form.errors)
        if form.is_valid():
            data = form.cleaned_data
            exp = Experiment(name = data.get("name"))
            print(data)
            #exp.save()
            #exp.samples.add(sample)
            return HttpResponseRedirect('thanks.html')
        else: print("what")
    else:
        form = ExperimentSubmissionForm()
        return render_to_response('experiment.html',{'form': form},
                context_instance=RequestContext(request))


def sample_request(request):
    results = []
    if request.method == 'GET':
        if request.GET.has_key(u'term'):
            value = request.GET[u'term']
            # Makes user has inputted at least 3 letters
            if len(value) > 2:
                sample_results = Sample.objects.filter(name__icontains=value)
                results = [ (x.__unicode__(), x.id) for x in sample_results ]
    response = json.dumps(results)
    return(HttpResponse(response, mimetype="application/json"))


@login_required(login_url='/weblab/accounts/login/')
def sequences(request):
    """ Initial pageload includes all data, no need to make an additional ajax
    calls.
    """
    return render_to_response('sequences.html',
                              context_instance=RequestContext(request))

weblab/templates/WBBase.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta charset="utf-8" />
        <title>{% block title %} WebLab {% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}styles/WBBase.css" media="screen" />
        <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.min.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/nav.js"></script>
        {% block header %} {% endblock %}
    </head>

<body>
    <!-- Todo switch to Twitter Bootstrap -->
    <div id="navigation">
        <ul id = "nav">
            <li><a href="/">Home </a> </li>
            <li><a href="/weblab/">Weblab </a>
                <ul>
                    <li><a href="/weblab/samples/">Samples</a></li>
                    <li><a href="/weblab/search/">Search</a>
                    <li><a href="/weblab/sequence/">Sequences</a></li>
                    <li><a href="/weblab/experiment/">Experiment</a></li>
                    <li><a href="/weblab/reagents/">Reagents</a></li>
                    <li><a href="/weblab/labs/">Manage Labs </a></li>
                    <li><a href="/weblab/colony/">Colony Managment </a></li>
                </ul>
            </li>
            <li><a href="#">About Us</a>
                <ul>
                    <li><a href="/weblab/about/">About Us</a></li>
                    <li><a href="/weblab/jobs/">Jobs</a></li>
                    <li><a href="/weblab/clients/">Clients</a></li>
                    <li><a href="/weblab/developers/">Developers</a></li>
                    <li><a href="/shoebox/">Blog</a></li>
                </ul>
            </li>
        {% if user.is_authenticated %}
            <li><a href="/weblab/accounts/logout/">Signout </a></li> 
        {% else %}
            <li><a href="/weblab/accounts/login/">Login</a></li> 
            <li><a href="/weblab/accounts/register/">Signup </a></li>
        {% endif %}
        </ul>
    </div>


    <div id="content">
        {% block content %}
        {% endblock %}
    </div>


    <div id="footer">
    </div>
</body>
</html>

weblab/templates/about.html
{% extends "WBBase.html" %}
{% load i18n %}

{% block content %}
<br />
<br />
<h1><u>Jeff Hsu </u></h1>
<h2>Chief Mad Scientist</h2> 
<p>  Jeff Hsu is a PhD candidate in the Molecular Medicine program at the Cleveland Clinic Lerner College of 
Medicine at Case Western Reserve University.  During his work on whole genome studies,
he has come to the realization for the need for a more scalable experimental process.
His current research is in identifying modifier genes that affect athersclerosis and the genetics of atrial fibrillation.  Python is his only true love, though he works mainly in R.  Javascript is cool too, he supposes. </p>

<h1><u> Joe Hsu </u></h1>
<h2></h2>
{% endblock %}

weblab/templates/experiment.html
{% extends "WBBase.html" %}
{% load compress %}
{% block header %}
<link rel="stylesheet"
href="{{STATIC_URL}}styles/smoothness/jquery-ui-1.8.14.custom.css" media="all" />
<script type="text/javascript" src="{{STATIC_URL}}js/csrf.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/js/jquery-ui.custom.min.js"></script>
<script>
    jQuery(function() {
    var selected_samples = new Array();
    var added_samples = new Array();

    function log(message) {
        jQuery("<div/>").text(message).prependTo("#log");
        jQuery("#log").attr("scrollTop", 0);
    }

    function addSelectable(elements) {
        jQuery("ol").append(elements);
        jQuery("#selectable").selectable();
    }
    
    jQuery('#id_samples').autocomplete({
        source: function( request, response) {
            jQuery.ajax({
                type: 'GET',
                url: '/weblab/sample_request',
                dataType: "json",
                data: {
                    featureClass: "P",
                    maxRows: 12,
                    term: request.term
                },
                success: function(data, status ) {
                    var temp_key = 0;
                    response($.map(data, function(item){
                    addSelectable("<li>"+item[0]+ "</li>");
                    selected_samples[temp_key] = item[1];
                    temp_key = temp_key + 1;

                        

                        return {
                        label: item[0],
                        value: item[1], 
                        }
                    
                    }));
                }
            });
        },
        minLength: 2,
        select: function( event, ui) {
            log( ui.item ? 
                ui.item.label :
                "Nothing selected, input was " + this.value );
            jQuery('id_sample_pk').attr('value', ui.item.label); 
            added_samples[ui.item.label] = ui.item.value;
            jQuery("#selectable").empty();
            console.log(added_samples);
            },
        open: function() {
            $( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
        },
        close: function() {
            $( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );

        }

    });
    jQuery("#selectable").selectable({
        selected: function(event, ui){
        }
    });
    jQuery("#add").click(function() {
        jQuery(".ui-selected").each(function() {
        var index = jQuery("#selectable li").index(this);
        log(this.innerHTML);
        console.log(selected_samples);
        added_samples[this.innerHTML] = selected_samples[index];
        }); 
        console.log(added_samples);   
        jQuery("#selectable").empty();
    });
});

</script>
<style>
    #feedback { font-size: 1.4em; }
    #selectable .ui-selecting { background: #FECA40; }
    #selectable .ui-selected { background: #F39814; color: white; }
    #selectable { list-style-type: none; margin: 0; padding: 0; width: 30%; }
    #selectable li { margin: 3px; padding: 0.4em; font-size: 1.4em; height:
        18px;}
</style>

{% endblock %}

{% block content %}
<br />
<br />
<h1> Create an experiment </h1>
<form action="", method = "POST">
    {% csrf_token %}
    {% for field in form %}
        <div class="ui-widget">
            {{ field.errors }}
            {{ field.label_tag }} : {{ field }}
        </div>
    {% endfor %}
    <input type="submit" value="submit" />
</form>

<ol  id="selectable">
</ol>
<button id="add">Add</button>
    <div class="ui-widget">
        Selected Samples:<div id="log" style="height: 200px; width: 300px; overflow: auto;" class="ui-widget-content"></div>
</div>
    </div>
{% endblock %}

weblab/templates/index.html
{% load compress %}
{% extends "base.html" %}

{% block header %}

{% endblock %}

{% block content %}
<h1>Scatter Brained </h1>
<h2> Genetics, Robotics, Stemcells, Buzzword, Buzzword   </h2>
<p> Welcome to my personal website.  </p>
<p> Check out Google web-gl <a href="hDP/">globe</a> adapted to serve genetic infromation from the
<a href="http://www.cephb.fr/en/hgdp/diversity.php/">Human Genome Diversity
    Panel</a> using Django as a backend</p>

<p> Also check out this amazing <a href="genome/">genome browser</a> written entirely in javascript
<a href="http://bioinformatics.oxfordjournals.org/content/27/6/889.short">Thomas Down.</a> </p>




{% endblock %}

weblab/templates/locations.html
{% extends "WBBase.html" %}
{% block title %} Locations {% endblock %}

{% block content %}

<p>Hi </p>

{% endblock %}

weblab/templates/login.html
{% extends "WBBase.html" %}
{% load url from future %}

{% block title %}
    Login
{% endblock %}

{% block content %}

<p>Hello</p>
{% if form.errors %}

// :TODO differentiate between username error and password erro
<p> Your username and password didn't match.  Please try again. </p>
{% endif %}

<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}

<table>
<tr>
    <td>{{form.username.label_tag }}</td>
    <td>{{form.username}}</td>
</tr>
<tr>
    <td>{{form.password.label_tag }}</td>
    <td>{{form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{next}}" />
</form>

{% endblock %}

weblab/templates/samples.html
{% extends "WBBase.html" %}
{% load verbatim %}
{% load compress %}


{% block title %} Samples {% endblock %}

{% block header %} 

{% compress js %}
  <script type="text/javascript" 
    src="{{STATIC_URL}}js/js/jquery-ui.custom.min.js"></script>
  <script type="text/javascript"
    src="{{STATIC_URL}}js/underscore-min.js"></script> 
  <script src="{{STATIC_URL}}js/backbone-min.js"></script>
  <script src="{{STATIC_URL}}js/backbone-tastypie.js"></script>
  <script type="text/javascript"
    src="{{STATIC_URL}}js/ICanHaz.min.js"></script>

  <script 
    src="{{STATIC_URL}}js/weblab/samples.js"></script>
  <script
    src="{{STATIC_URL}}js/weblab/sampleViews.js"></script>
{% endcompress %}

{% verbatim %}
<script type="text/html" id="sample_template">
    <tr>
    <td><a class="sample_name" href="#"> {{name}} </a></td>
    <td> {{ description }} </td>
    </tr>
</script>
{% endverbatim %}
  
  <link rel="stylesheet"
href="{{STATIC_URL}}styles/tablesorter/blue/style.css" media="all" />
  <script type="text/javascript" src="{{STATIC_URL}}/js/jquery.tablesorter.js"></script>

<script>
    jQuery(document).ready(function() {
        $("#sampletable").tablesorter();
        });
</script>


{% endblock %}

{% block content %}
<br />
<br />
<h1> Samples </h1>

<div id="app">
</div>

<table id="sampletable" class="tablesorter">
    <thead>
    <tr>
        <th>Date</th>
        <th>Name</th>
        <th>Description</th>
        <th>Storage</th>
    </tr>
    </thead>
    <tbody>
    {% for sample in samples %}
    <tr>
        <td>{{ sample.created }}</td>
        <td>{{sample.name}}</td>
        <td><a href="/weblab/samples/{{sample.id}}">{{ sample.description }}</a></td>
        <td>{{ sample.storage}} </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<br />
<a href="/addSample">Add sample</a>

<script> 
SEQUENCE_API="{% url api_dispatch_list resource_name='sample' api_name='v1'%}";
var sample_collection = new SampleCollection();
var samples_view = new SampleApp({el: $("#app"), collection :
    sample_collection});
sample_collection.fetch();
</script>
{% endblock %}

weblab/templates/thanks.html
{% extends "WBBase.html" %}


{% block content %}
<br />
<br />
<p>
Thanks for using weblab
</p>

{% endblock %}